#pragma once


namespace MYD3D
{
	//내적
	FLOAT MYD3DXVec3Dot( CONST MYD3DXVECTOR3* pV1, CONST MYD3DXVECTOR3* pV2 );

	//외적
	MYD3DXVECTOR3* MYD3DXVec3Cross( MYD3DXVECTOR3* pOut, CONST MYD3DXVECTOR3* pV1, CONST MYD3DXVECTOR3* pV2 );

	//길이
	FLOAT MYD3DXVec3Length( CONST MYD3DXVECTOR3* pV1 );

	//정규화
	MYD3DXVECTOR3* MYD3DXVec3Normalize( MYD3DXVECTOR3* pOut, CONST MYD3DXVECTOR3* pV1 );

	//방향 벡터구할때 유용한 함수 pV1 에서 pV2 를 빼서 방향 벡터를 반환한다.
	MYD3DXVECTOR3* MYD3DXVec3Subtract( MYD3DXVECTOR3* pOut, CONST MYD3DXVECTOR3* pV1, CONST MYD3DXVECTOR3* pV2 );

	//내적된 코사인 값에서 각도만 뽑아내서 얻기
	FLOAT MYD3DXVec3DotAngle( CONST MYD3DXVECTOR3* pV1, CONST MYD3DXVECTOR3* pV2 );
}